/**
 * Generated by the build (scripts/activities/plugin.ts): every native
 * Activity from parousia-project/activities that passed its checks, as its
 * manifest and its module. Empty when the build found no Activity sources.
 */
declare module "parousia:activities" {
  import type { ActivityManifest, NativeModule } from "./activities/manifest";

  export const native: ReadonlyArray<{ manifest: ActivityManifest; module: NativeModule }>;
}
